version: "3.6"
services:
  mosquitto:
    container_name: mosquitto
    restart: always
    image: eclipse-mosquitto
    ports:
      - 1883:1883

  rpi_ws281x:
    container_name: rpi_ws281x
    restart: unless-stopped
    build:
    privileged: true
    depends_on:
      - mosquitto
    volumes:
      - ./ws281x.py:/app/ws281x.py
    environment:
      - LED_GPIO=18
      - LED_COUNT=167
      - MQTT_BROKER=mosquitto
      - MQTT_USER=user
      - MQTT_PASSWORD=123456
